# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-25 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [(b'roadsheet', '0001_initial'), (b'roadsheet', '0002_auto_20171215_0041'), (b'roadsheet', '0003_auto_20171215_0138'), (b'roadsheet', '0004_auto_20171215_0204'), (b'roadsheet', '0005_auto_20171215_0222'), (b'roadsheet', '0006_auto_20171222_1608'), (b'roadsheet', '0007_carmodel_manufacturer'), (b'roadsheet', '0008_remove_cars_car_manufacturer'), (b'roadsheet', '0009_auto_20171225_1208'), (b'roadsheet', '0010_auto_20171225_1233'), (b'roadsheet', '0011_auto_20171225_1710'), (b'roadsheet', '0012_auto_20171225_1714'), (b'roadsheet', '0013_auto_20171225_1752'), (b'roadsheet', '0014_roadsheets_deleted'), (b'roadsheet', '0015_auto_20171225_2209'), (b'roadsheet', '0016_auto_20180123_1700'), (b'roadsheet', '0017_auto_20180125_1431'), (b'roadsheet', '0018_tmcsheet'), (b'roadsheet', '0019_doctabletsim_aparted_timestamp')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Roadsheets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadsheet.Drivers')),
                ('execution_datetime', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('previous_record', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='roadsheet.Roadsheets')),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_number', models.CharField(default='', max_length=4)),
                ('reg_number', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tablets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_code', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='roadsheets',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadsheet.Cars'),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='CarManufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_name', models.CharField(default=0, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default=0, max_length=100)),
                ('manufacturer', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='roadsheet.CarManufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='DriverWorkload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workload', models.CharField(default=0, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='drivers',
            name='callsign',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='roadsheets',
            name='draft',
            field=models.NullBooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='middle_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='cars',
            name='car_model',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='roadsheet.CarModel'),
        ),
        migrations.RemoveField(
            model_name='roadsheets',
            name='previous_record',
        ),
        migrations.AddField(
            model_name='roadsheets',
            name='operator',
            field=models.CharField(default='admin', editable=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roadsheets',
            name='active',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='roadsheets',
            name='workload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadsheet.DriverWorkload'),
        ),
        migrations.CreateModel(
            name='TabletStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='roadsheets',
            name='deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='roadsheets',
            name='closed_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SimCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20)),
                ('sn', models.CharField(blank=True, max_length=50)),
                ('operator', models.CharField(blank=True, max_length=50)),
                ('in_use', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocTabletSim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parted_timestamp', models.DateTimeField(auto_now_add=True)),
                ('sim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadsheet.SimCards')),
                ('tablet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadsheet.Tablets')),
                ('aparted_timestamp', models.DateTimeField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TMCSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
