# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-14 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('roadsheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadsheets',
            name='board_number',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='roadsheets',
            name='execution_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
