# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-14 22:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadsheet', '0002_auto_20171215_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tablets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='roadsheets',
            name='board_number',
        ),
        migrations.AddField(
            model_name='roadsheets',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roadsheets',
            name='previous_record',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='roadsheet.Roadsheets'),
        ),
        migrations.AddField(
            model_name='roadsheets',
            name='car',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='roadsheet.Cars'),
        ),
        migrations.AddField(
            model_name='roadsheets',
            name='tablet',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='roadsheet.Tablets'),
        ),
    ]
