# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-25 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadsheet', '0002_auto_20180125_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocAddTmc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('roadsheet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='roadsheet.Roadsheets')),
                ('tablet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='roadsheet.Tablets')),
            ],
        ),

    ]
