# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-14 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadsheet', '0003_auto_20171215_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadsheets',
            name='car',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='roadsheet.Cars'),
        ),
        migrations.AlterField(
            model_name='roadsheets',
            name='tablet',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='roadsheet.Tablets'),
        ),
    ]
