# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-14 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadsheet', '0004_auto_20171215_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablets',
            name='internal_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tablets',
            name='model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tablets',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
