# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-22 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadsheet', '0005_auto_20171215_0222'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarManufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_name', models.CharField(default=0, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default=0, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DriverWorkload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workload', models.CharField(default=0, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='cars',
            name='board_number',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cars',
            name='reg_number',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drivers',
            name='callsign',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='roadsheets',
            name='draft',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='middle_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='cars',
            name='car_manufacturer',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='roadsheet.CarManufacturer'),
        ),
        migrations.AddField(
            model_name='cars',
            name='car_model',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='roadsheet.CarModel'),
        ),
    ]
