# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-30 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadsheet', '0005_auto_20180130_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadsheets',
            name='active',
        ),
        migrations.RemoveField(
            model_name='roadsheets',
            name='draft',
        ),
        migrations.AddField(
            model_name='roadsheets',
            name='creation_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='roadsheets',
            name='closed_datetime',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='roadsheets',
            name='execution_datetime',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
