# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-30 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadsheet', '0006_auto_20180130_2357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roadsheets',
            old_name='closed_datetime',
            new_name='closed_timestamp',
        ),
        migrations.RenameField(
            model_name='roadsheets',
            old_name='execution_datetime',
            new_name='execution_timestamp',
        ),
    ]
