# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-22 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadsheet', '0007_carmodel_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='car_manufacturer',
        ),
    ]
