# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-30 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadsheet', '0007_auto_20180131_0013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roadsheets',
            old_name='operator',
            new_name='operator_close',
        ),
        migrations.AddField(
            model_name='roadsheets',
            name='operator_open',
            field=models.CharField(default=0, editable=False, max_length=100),
            preserve_default=False,
        ),
    ]
