# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-31 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadsheet', '0008_auto_20180131_0227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docqualitytablet',
            name='quality',
        ),
        migrations.AddField(
            model_name='docqualitytablet',
            name='quality',
            field=models.ManyToManyField(to='roadsheet.TabletQuality'),
        ),
    ]
