# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-25 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadsheet', '0008_remove_cars_car_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='manufacturer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='roadsheet.CarManufacturer'),
        ),
        migrations.AlterField(
            model_name='roadsheets',
            name='draft',
            field=models.NullBooleanField(default=True),
        ),
    ]
