# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-25 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadsheet', '0009_auto_20171225_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadsheets',
            name='previous_record',
        ),
        migrations.AddField(
            model_name='roadsheets',
            name='operator',
            field=models.CharField(default='admin', editable=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roadsheets',
            name='active',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='roadsheets',
            name='draft',
            field=models.NullBooleanField(default=True, editable=False),
        ),
    ]
