# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-01 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadsheet', '0011_auto_20180131_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='docrequest',
            name='roadsheet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='roadsheet.Roadsheets'),
        ),
        migrations.AddField(
            model_name='docrequest',
            name='tablet_break_request',
            field=models.ManyToManyField(to='roadsheet.TabletQuality'),
        ),
    ]
