# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-25 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadsheet', '0011_auto_20171225_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='car_state',
        ),
        migrations.AddField(
            model_name='roadsheets',
            name='car_fullgas',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roadsheets',
            name='car_state',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='CarStates',
        ),
    ]
