# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-25 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadsheet', '0012_auto_20171225_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabletStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='roadsheets',
            name='car',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='roadsheet.Cars'),
        ),
        migrations.AlterField(
            model_name='roadsheets',
            name='tablet',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='roadsheet.Tablets'),
        ),
        migrations.AddField(
            model_name='tablets',
            name='tablet_status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='roadsheet.TabletStatus'),
            preserve_default=False,
        ),
    ]
