# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-23 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadsheet', '0015_auto_20171225_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20)),
                ('sn', models.CharField(blank=True, max_length=50)),
                ('operator', models.CharField(blank=True, max_length=50)),
                ('in_use', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='roadsheets',
            name='car_fullgas',
        ),
        migrations.RemoveField(
            model_name='roadsheets',
            name='car_state',
        ),
        migrations.RemoveField(
            model_name='roadsheets',
            name='tablet',
        ),
        migrations.AlterField(
            model_name='roadsheets',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadsheet.Cars'),
        ),
        migrations.AlterField(
            model_name='roadsheets',
            name='workload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadsheet.DriverWorkload'),
        ),
    ]
