# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-01 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadsheet', '0016_auto_20180201_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docrequest',
            name='comment',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='docrequest',
            name='roadsheet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='roadsheet.Roadsheets'),
        ),
    ]
