# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-09 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadsheet', '0018_docendday'),
    ]

    operations = [
        migrations.AddField(
            model_name='docendday',
            name='t_accessible',
            field=models.ManyToManyField(related_name='tab_in_use', to='roadsheet.Tablets'),
        ),
    ]
