# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-09 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadsheet', '0019_docendday_t_accessible'),
    ]

    operations = [
        migrations.AddField(
            model_name='docendday',
            name='t_in_diagnostic',
            field=models.ManyToManyField(related_name='tab_diagnostic', to='roadsheet.Tablets'),
        ),
        migrations.AlterField(
            model_name='docendday',
            name='t_accessible',
            field=models.ManyToManyField(related_name='tab_access', to='roadsheet.Tablets'),
        ),
    ]
