# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-13 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadsheet', '0021_auto_20180209_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('inn', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
                ('service_address', models.CharField(max_length=100)),
                ('mechanic_name', models.CharField(max_length=100)),
                ('mechanic_address', models.CharField(max_length=100)),
            ],
        ),
    ]
