# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-13 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadsheet', '0022_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='mechanic_address',
        ),
    ]
