# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-13 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadsheet', '0023_remove_organization_mechanic_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrLicenseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=0, max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='drivers',
            name='license_date',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='drivers',
            name='license_number',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='drivers',
            name='license_category',
            field=models.ManyToManyField(to='roadsheet.DrLicenseCategory'),
        ),
    ]
