# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-19 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadsheet', '0024_auto_20180213_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='tichnical_chief',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
