# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-19 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadsheet', '0025_organization_tichnical_chief'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='tichnical_chief',
            new_name='technical_chief',
        ),
    ]
