# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-19 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadsheet', '0027_auto_20180219_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='docrequest',
            name='timestamp_in_service',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
