# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-19 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadsheet', '0029_auto_20180219_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[(1, 'Operator'), (2, 'Serviceman')], max_length=1),
        ),
        migrations.DeleteModel(
            name='UserRoles',
        ),
    ]
