# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-27 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadsheet', '0034_auto_20180226_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='docrequest',
            name='defect_desc',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
