# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-27 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadsheet', '0035_docrequest_defect_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField(blank=True, null=True)),
                ('exp_date', models.DateTimeField(blank=True, null=True)),
                ('document_number', models.CharField(editable=False, max_length=100)),
                ('company_name', models.CharField(editable=False, max_length=100)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadsheet.Cars')),
            ],
        ),
    ]
