# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-27 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadsheet', '0036_insurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='exp_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
