# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-27 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadsheet', '0037_auto_20180227_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='TO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('exp_date', models.DateField(blank=True, null=True)),
                ('document_number', models.CharField(max_length=100)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadsheet.Cars')),
            ],
        ),
        migrations.AlterField(
            model_name='insurance',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='document_number',
            field=models.CharField(max_length=100),
        ),
    ]
