# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-27 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadsheet', '0038_auto_20180227_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablets',
            name='timestamp_foolished',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tablets',
            name='timestamp_lost',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
