# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-28 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadsheet', '0041_auto_20180227_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docendday',
            name='t_accessible',
        ),
        migrations.RemoveField(
            model_name='docendday',
            name='t_in_diagnostic',
        ),
        migrations.RemoveField(
            model_name='docendday',
            name='t_in_use',
        ),
        migrations.DeleteModel(
            name='DocEndDay',
        ),
    ]
